# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        m = {}
        for i in s:
            m[i] = m.get(i, 0) + 1
        for i in t:
            m[i] = m.get(i, 0) - 1
        for i in m:
            if m[i] == -1:
                return i

s = "abcd"
t = "abcde"
print Solution().findTheDifference(s, t)

# no need to use a map
# just xor all the characters to see what is left
